# Generated by Django 3.0.7 on 2020-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admission',
            name='student_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Promocode',
        ),
    ]
