# Generated by Django 3.0.3 on 2020-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20200620_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='student_roll',
        ),
        migrations.AddField(
            model_name='admission',
            name='registered_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
