# Generated by Django 3.0.3 on 2020-06-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0006_auto_20200620_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_announced', models.DateTimeField(auto_now=True)),
                ('announcement_type', models.CharField(choices=[('Custom', 'Custom'), ('Public', 'Public')], max_length=10)),
                ('class_name', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='classroom.Grade')),
            ],
        ),
    ]
