# Generated by Django 3.0.3 on 2020-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
