# Generated by Django 3.0.3 on 2020-06-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_content_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(max_length=100),
        ),
    ]
