# Generated by Django 3.0.3 on 2020-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200615_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.CharField(default='content', max_length=100),
            preserve_default=False,
        ),
    ]
