# Generated by Django 3.1 on 2020-08-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_contents', '0002_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
    ]
