# Generated by Django 3.1 on 2020-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_contents', '0003_remove_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
