# Generated by Django 3.1 on 2020-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_contents', '0004_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
