# Generated by Django 3.1 on 2020-08-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_contents', '0005_auto_20200812_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(),
        ),
    ]
