# Generated by Django 3.1 on 2020-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_contents', '0006_auto_20200812_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
