# Generated by Django 3.0.3 on 2020-06-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20200616_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('question_file', models.FileField(upload_to='questions')),
                ('submission_date', models.DateField()),
                ('given_at', models.DateTimeField(auto_now=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='answers')),
                ('checked', models.BooleanField(default=False, null=True)),
                ('received_grade', models.PositiveIntegerField(blank=True, default=0)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignment.Assignment')),
            ],
        ),
    ]
