# Generated by Django 3.0.3 on 2020-06-20 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(upload_to='questions', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment_file',
            field=models.FileField(upload_to='answers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf', 'docx'])]),
        ),
    ]
