# Generated by Django 3.0.3 on 2020-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200620_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_time',
            field=models.DateField(auto_now=True),
        ),
    ]
