# Generated by Django 3.0.7 on 2020-06-23 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignmentsubmission_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(upload_to='questions', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf', 'docx', 'jpg'])]),
        ),
    ]
